apiVersion: v1
kind: Service
metadata:
  name: callback-service
  namespace: kivebpf-system
spec:
  selector:
    app.kubernetes.io/name: callback-pod
  ports:
    - protocol: TCP
      port: 9376
      targetPort: 8090
