apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: manager
    app.kubernetes.io/name: kivebpf
    app.kubernetes.io/managed-by: kustomize
  name: system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: manager
  namespace: system
  labels:
    control-plane: manager
    app.kubernetes.io/name: kivebpf
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    matchLabels:
      control-plane: manager
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: manager
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      securityContext:
        runAsNonRoot: true
      containers:
      - command:
        - /manager
        args:
          - --kive-policy-health-probe-bind-address=:8081
          - --kive-data-health-probe-bind-address=:8082
          - --kive-pod-health-probe-bind-address=:8083
          # - --metrics-bind-address=0  # Disable metrics (default)
        image: kivebpf
        name: kivebpf
        securityContext:
          runAsNonRoot: false
          privileged: true
        volumeMounts:
          - name: containerd-sock
            mountPath: /run/containerd/containerd.sock
            readOnly: false
          - name: proc
            mountPath: /host/proc
            readOnly: true
          - name: realproc
            mountPath: /host/real/proc
            readOnly: true
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
      serviceAccountName: manager
      terminationGracePeriodSeconds: 10
      volumes:
        - name: containerd-sock
          hostPath:
            path: /run/containerd/containerd.sock
            type: Socket
        - name: proc
          hostPath:
            path: /proc
            type: Directory
        - name: realproc
          hostPath:
            path: /host/real/proc
            type: Directory
