apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hive-operator
  name: hive-operator-hivedata-editor-role
rules:
- apiGroups:
  - hive.com
  resources:
  - hivedata
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hive.com
  resources:
  - hivedata/status
  verbs:
  - get
