# permissions for end users to view hivedata.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: hive-operator
    app.kubernetes.io/managed-by: kustomize
  name: hivedata-viewer-role
rules:
- apiGroups:
  - hive.dynatrace.com
  resources:
  - hivedata
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hive.dynatrace.com
  resources:
  - hivedata/status
  verbs:
  - get
