# permissions for end users to edit hivedata.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: hive-operator
    app.kubernetes.io/managed-by: kustomize
  name: hivedata-editor-role
rules:
- apiGroups:
  - hive-operator.com
  resources:
  - hivedata
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hive-operator.com
  resources:
  - hivedata/status
  verbs:
  - get
