# permissions for end users to view hives.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: hive-operator
    app.kubernetes.io/managed-by: kustomize
  name: hive-viewer-role
rules:
- apiGroups:
  - hive-operator.com
  resources:
  - hives
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hive-operator.com
  resources:
  - hives/status
  verbs:
  - get
