# permissions for end users to edit hives.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: hive-operator
    app.kubernetes.io/managed-by: kustomize
  name: hive-editor-role
rules:
- apiGroups:
  - hive.com
  resources:
  - hives
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hive.com
  resources:
  - hives/status
  verbs:
  - get
