---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - deployments/status
  - pods/status
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hive.com
  resources:
  - hivedata
  - hives
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hive.com
  resources:
  - hivedata/finalizers
  - hives/finalizers
  verbs:
  - update
- apiGroups:
  - hive.com
  resources:
  - hivedata/status
  - hives/status
  verbs:
  - get
  - patch
  - update
