---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - deployments/status
  - pods/status
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kivebpf.san7o.github.io
  resources:
  - kivedata
  - kivepolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kivebpf.san7o.github.io
  resources:
  - kivedata/finalizers
  - kivepolicies/finalizers
  verbs:
  - update
- apiGroups:
  - kivebpf.san7o.github.io
  resources:
  - kivedata/status
  - kivepolicies/status
  verbs:
  - get
  - patch
  - update
