---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - deployments/status
  - pods/status
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hive-operator.com
  resources:
  - hivedata
  - hivepolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hive-operator.com
  resources:
  - hivedata/finalizers
  - hivepolicies/finalizers
  verbs:
  - update
- apiGroups:
  - hive-operator.com
  resources:
  - hivedata/status
  - hivepolicies/status
  verbs:
  - get
  - patch
  - update
