apiVersion: operators.coreos.com/v2alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: kivebpf.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: Kive is an eBPF-powered file access monitoring Kubernetes operator.
  displayName: kive
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - ebpf
  - monitoring
  links:
  - name: Kive Operator
    url: https://kivebpf.domain
  maintainers:
  - email: santigio2003@gmail.com
    name: Giovanni
  maturity: alpha
  provider:
    name: kivebpf.san7o.github.io
  version: 0.0.0
