apiVersion: hive.com/v1alpha1
kind: HivePolicy
metadata:
  labels:
    app.kubernetes.io/name: hive-operator
  name: hive-sample-policy3
  namespace: hive-operator-system
spec:
  path: /etc/shadow
  match:
    labels:
      security-level: high 
