apiVersion: hive-operator.com/v1alpha1
kind: HivePolicy
metadata:
  labels:
    app.kubernetes.io/name: hive-operator
  finalizers:
    - hive-operator.com/finalizer
  name: hive-sample-policy
  namespace: hive-operator-system
spec:
  traps:
  - path: /secret.txt
    create: true
    mode: 444
    matchAny:
    - pod: nginx-pod
      namespace: default
      matchLabels:
        security-level: high
