apiVersion: hive-operator.com/v1alpha1
kind: HivePolicy
metadata:
  labels:
    app.kubernetes.io/name: hive-operator
  finalizers:
    - hive-operator.com/finalizer
  name: hive-sample-policy-regex2
  namespace: hive-operator-system
spec:
  traps:
    - path: /regex2.txt
      create: true
      mode: 444
      matchAny:
        - pod: nginx-pod
          namespace: default
          container-name: "123.*"
