apiVersion: hive.com/v1alpha1
kind: HiveData
metadata:
  labels:
    app.kubernetes.io/name: hive-operator
    app.kubernetes.io/managed-by: kustomize
  name: hive-sample-data
spec:
  dev-id: 87
  inode-no: 2865504
  kernel-id: dc4250f6-f06e-4ea3-86eb-f7a2d8ee01de
  path: /secret.txt
  match:
    ip: 10.244.1.2
    namespace: default
    pod: nginx-pod
    label:
    - key: security-level
      value: high
