apiVersion: hive-operator.com/v1alpha1
kind: HivePolicy
metadata:
  labels:
    app.kubernetes.io/name: hive-operator
  finalizers:
    - hive-operator.com/finalizer
  name: hive-sample-policy3
  namespace: hive-operator-system
spec:
  path: /etc/shadow
  match:
    matchLabels:
      security-level: high 
