apiVersion: hive.com/v1alpha1
kind: HivePolicy
metadata:
  labels:
    app.kubernetes.io/name: hive-operator
    app.kubernetes.io/managed-by: kustomize
  name: hive-sample-policy
spec:
  path: /secret.txt
  create: true
  mode: 444
  match:
    pod: nginx-pod
    namespace: default
    label:
    - key: security-level
      value: high
