apiVersion: kivebpf.san7o.github.io/v2alpha1
kind: KivePolicy
metadata:
  labels:
    app.kubernetes.io/name: kivebpf
  name: kive-sample-policy-regex2
  namespace: kivebpf-system
spec:
  traps:
    - path: /regex2.txt
      create: true
      mode: 444
      matchAny:
        - pod: nginx-pod
          namespace: default
          containerName: "regex:123.*"
