//go:build !ignore_autogenerated

/*
                    GNU GENERAL PUBLIC LICENSE
                       Version 2, June 1991

 Copyright (C) 1989, 1991 Free Software Foundation, Inc.,
 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
 Everyone is permitted to copy and distribute verbatim copies
 of this license document, but changing it is not allowed.
*/

// SPDX-License-Identifier: GPL-2.0-only

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Hive) DeepCopyInto(out *Hive) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Hive.
func (in *Hive) DeepCopy() *Hive {
	if in == nil {
		return nil
	}
	out := new(Hive)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Hive) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HiveList) DeepCopyInto(out *HiveList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Hive, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HiveList.
func (in *HiveList) DeepCopy() *HiveList {
	if in == nil {
		return nil
	}
	out := new(HiveList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HiveList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HivePolicy) DeepCopyInto(out *HivePolicy) {
	*out = *in
	out.Match = in.Match
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HivePolicy.
func (in *HivePolicy) DeepCopy() *HivePolicy {
	if in == nil {
		return nil
	}
	out := new(HivePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HivePolicyMatch) DeepCopyInto(out *HivePolicyMatch) {
	*out = *in
	out.Label = in.Label
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HivePolicyMatch.
func (in *HivePolicyMatch) DeepCopy() *HivePolicyMatch {
	if in == nil {
		return nil
	}
	out := new(HivePolicyMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HiveStatus) DeepCopyInto(out *HiveStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HiveStatus.
func (in *HiveStatus) DeepCopy() *HiveStatus {
	if in == nil {
		return nil
	}
	out := new(HiveStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LabelType) DeepCopyInto(out *LabelType) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LabelType.
func (in *LabelType) DeepCopy() *LabelType {
	if in == nil {
		return nil
	}
	out := new(LabelType)
	in.DeepCopyInto(out)
	return out
}
