FROM ubuntu:22.04

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    clang \
    llvm \
    libelf-dev \
    gcc \
    make \
    pkg-config \
    git \
    build-essential \
    iproute2 \
    iputils-ping \
    net-tools \
    python3 \
    python3-pip \
    wget \
    bpfcc-tools \
    libbpf-dev \
    tmux \
    vim \
    && rm -rf /var/lib/apt/lists/*

ENV GO_VERSION=1.24.0
RUN wget https://go.dev/dl/go${GO_VERSION}.linux-amd64.tar.gz \
    && rm -rf /usr/local/go \
    && tar -C /usr/local -xzf go${GO_VERSION}.linux-amd64.tar.gz \
    && rm go${GO_VERSION}.linux-amd64.tar.gz

ENV PATH="/usr/local/go/bin:${PATH}"
ENV GOPATH=/go
ENV PATH="${GOPATH}/bin:${PATH}"

WORKDIR /workspace

CMD ["/bin/bash"]
